var ERC721Basic = artifacts.require("ERC721Basic");
// var ERC721Basic = artifacts.require("./ERC721Basic.sol");
// var ERC721Basic = artifacts.require("openzeppelin-solidity/contracts/token/ERC721/ERC721Basic.sol");
var ERC721Enumerable = artifacts.require("ERC721Enumerable");
var ERC721Metadata = artifacts.require("ERC721Metadata");
var ERC721 = artifacts.require("ERC721");
// var ERC721 = artifacts.require("./ERC721.sol");
// var ERC721 = artifacts.require("openzeppelin-solidity/contracts/token/ERC721/ERC721.sol");
var DeprecatedERC721 = artifacts.require("DeprecatedERC721");
// var DeprecatedERC721 = artifacts.require("./DeprecatedERC721.sol");
// var DeprecatedERC721 = artifacts.require("openzeppelin-solidity/contracts/token/ERC721/DeprecatedERC721.sol");
var Ownable = artifacts.require("Ownable");
// var Ownable = artifacts.require("./Ownable.sol");
// var Ownable = artifacts.require("openzeppelin-solidity/contracts/ownership/Ownable.sol");
var SafeMath = artifacts.require("SafeMath");
// var SafeMath = artifacts.require("./SafeMath.sol");
// var SafeMath = artifacts.require("openzeppelin-solidity/contracts/math/SafeMath.sol");
var ZombieFactory = artifacts.require("ZombieFactory");
// var ZombieFactory = artifacts.require("./ZombieFactory.sol");
var KittyInterface = artifacts.require("KittyInterface");
var ZombieFeeding = artifacts.require("ZombieFeeding");
// var ZombieFeeding = artifacts.require("./ZombieFeeding.sol");
var ZombieAttack = artifacts.require("ZombieAttack");
// var ZombieAttack = artifacts.require("./ZombieAttack.sol");
var ZombieHelper = artifacts.require("ZombieHelper");
// var ZombieHelper = artifacts.require("./ZombieHelper.sol");
var ZombieOwnership = artifacts.require("ZombieOwnership");
// var ZombieOwnership = artifacts.require("./ZombieOwnership.sol");

module.exports = function(deployer) {
  // deployer.deploy(ERC721Basic);
	// deployer.deploy(ERC721Enumerable);
	// deployer.deploy(ERC721Metadata);
	// deployer.deploy(ERC721);
	// deployer.deploy(DeprecatedERC721);
	// deployer.deploy(Ownable);
	// deployer.deploy(SafeMath);
	deployer.deploy(ZombieFactory);
	// deployer.deploy(KittyInterface);
	deployer.deploy(ZombieFeeding);
	deployer.deploy(ZombieAttack);
	deployer.deploy(ZombieHelper);
	deployer.deploy(ZombieOwnership);
};
